name: Tests

on:
  push

jobs:
  screenshot:
    name: Screenshot
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#        width: [1200, 992, 768, 600]
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1.0.0

    - name: Capture Screenshot
#      id: screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/for-memory/Websites-Screenshots
        destination: Screenshot001.png
        full-page: true
#        width: ${{ matrix.width }}
